version: "3.8"

services:
  db-shopping-cart:
    image: postgres:13
    container_name: db-shopping-cart
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping-cart
    volumes:
      - ./data/db-shopping-cart:/var/lib/postgresql/data
