server:
  port: 8080
spring:
  application:
    name: shopping-cart
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart
    username: root
    password: pwd
logging:
  level:
    org:
      springframework:
        jdbc: debug
    web: debug

